name: Production Build, Push Docker images and Deployment

on:
  push:
    branches:
      - "main"
    pull_request:  
 

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/test:v${{ steps.tag_version.outputs.new_tag }}

    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Configure SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest Docker Compose file
      run: scp sergei@104.154.203.42:/home/sergei/app/docker-compose.yml .

    - name: Update Docker Compose file with latest image
      run: sed -i "s/image: test:v[0-9].[0-9].[0-9]/image: test:v${{ steps.tag_version.outputs.new_tag }}/g" docker-compose.yml

    - name: Deploy application with Docker Compose
      run: ssh -o StrictHostKeyChecking=no sergei@104.154.203.42 "cd /home/sergei/app && docker-compose pull && docker-compose up -d"      
    