on:
  release:
    types: [published]
    branches: [main]
name: release-main
jobs:
  Release:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.DOCKER_PUSHER_SERVICE_ACCOUNT_KEY }}'  

      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up gcloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Configure Docker 
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev  

      - name: Build docker image
        run:  docker build . -t europe-north1-docker.pkg.dev/crucial-runner-370615/docker-repo/t-bot:${RELEASE_VERSION}
        env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Push to Google Container Registry
        run:  docker push  -a europe-north1-docker.pkg.dev/crucial-runner-370615/docker-repo/t-bot:${RELEASE_VERSION}
        env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}    

      # - name: Deploy to Cloud Run
      #   id: deploy
      #   uses: google-github-actions/deploy-cloudrun@v0
      #   with:
      #     service: buycheaper-bot
      #     region: europe-north1
      #     project: crucial-runner-370615
      #     image: europe-north1-docker.pkg.dev/crucial-runner-370615/docker-repo/t-bot:${RELEASE_VERSION}
      #   env:
      #       RELEASE_VERSION: ${{ steps.vars.outputs.tag }}              
    